version: "3"

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 81:80
      - 446:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - dev-network
  helloworld:
    build: ./services/helloworld/.
    restart: always
    environment:
      VIRTUAL_HOST: helloworld.docker
    volumes:
      - ./services/helloworld/src:/var/www/html/helloworld/public
    networks:
      - dev-network

networks:
  dev-network:
    external: true
